export const titulosProfesionales = [
  "Maestro Mayor de Obras",
  "Técnico Constructor",
  "Técnico Mecánico Electricista",
  "Técnico Constructor Hidráulico",
  "Técnico Químico",
  "Técnico Superior Agrícola Ganadero",
  "Electrotécnico",
  "Técnico Mecánico",
  "Técnico Mecánico en Automotores",
  "Técnico en Higiene y Seguridad Alimentaria",
  "Técnico Superior en Alimentos",
  "Auxiliar Técnico Mecánico Tornero",
  "Técnico Superior en Decoración de Interiores",
  "Técnico Electromecánico",
  "Técnico en Electrónica (Comunicaciones)",
  "Técnico en Saneamiento",
  "Técnico Superior en Tecnología de Alimentos",
  "Técnico en Industrias Lácteas",
  "Perito Accidentólogo",
  "Bachiller Técnico en Electromecánica",
  "Técnico Sup. en Producción Agrícola-Ganadera",
  "Técnico Constructor Universitario",
  "Técnico en Computación",
  "Analista de Sistemas de Computación",
  "Técnico en Electrónica",
  "Técnico en Automotores",
  "Técnico en Higiene y Seguridad del Trabajo",
  "Analista Programador",
  "Analista Programador de Computación",
  "Agrónomo General",
  "Técnico Electricista",
  "Técnico Mec. Especialidad Máq. y Herramientas",
  "Técnico en Minería",
  "Técnico Analista Programador",
  "Técnico Sup. en Higiene y Seg. del Trabajo",
  "Auxiliar Técnico Electricista",
  "Auxiliar Técnico Electrónico",
  "Técnico Agrónomo",
  "Bachiller Sup. en Ambientación y Dec. de Interiores",
  "Auxiliar Técnico de Instalaciones Eléctricas",
  "Licenciado en Diseño",
  "Técnico en Informática",
  "Técnico Sup. en Publicidad",
  "Bachiller Técnico Auxiliar Electricista",
  "Técnico Superior en Informática",
  "Bachiller con Orientación Agraria",
  "Agrotécnico",
  "Técnico Sup. en Análisis de Alimentos",
  "Analista de Sistemas",
  "Técnico Sup. en Organización Industrial",
].sort((a, b) => a.localeCompare(b, "es"));
