services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: cpt_app
      POSTGRES_PASSWORD: 6aXGNndX0LyNMvqcYbr8E4hf
      POSTGRES_DB: cpt_app
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cpt_app -d cpt_app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
